Repository bcgov/nr-compliance-enforcement, pull requests merged in 2023-12, with the labels that each got.

#216 Protection against long data on list view
  frontend/src/app/components/containers/complaints/list-items/allegation-complaint-list-item.tsx
  frontend/src/app/components/containers/complaints/list-items/wildlife-complaint-list-item.tsx
  frontend/src/assets/sass/complaint.scss
Labels: bug

#218 Popup on map should be community + tests
  frontend/cypress/e2e/complaints-on-map-view.cy.ts
  frontend/src/app/components/mapping/complaint-summary-popup.tsx
Labels: bug

#210 feature/CE-104 upload an attachment to an existing complaint
  backend/db/migrations/R__Configuration-values.sql
  frontend/cypress/e2e/complaint-attachments.cy.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/common/api.ts
  frontend/src/app/common/methods.tsx
  frontend/src/app/components/common/attachment-slide.tsx
  frontend/src/app/components/common/attachment-upload.tsx
  frontend/src/app/components/common/attachments-carousel.tsx
  frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx
  frontend/src/app/constants/configurations.ts
  frontend/src/app/store/reducers.ts
  frontend/src/app/store/reducers/app.ts
  frontend/src/app/store/reducers/attachments.ts
  frontend/src/app/store/reducers/objectstore.ts
  frontend/src/app/types/coms/object.ts
  frontend/src/app/types/state/attachments-state.ts
  frontend/src/assets/sass/carousel.scss
Labels: enhancement

#223 feature/CE-32-Add-Attachments-When-Creating-New-Complaint
  frontend/cypress/e2e/allegation-details-create.cy.ts
  frontend/cypress/e2e/complaint-attachments.cy.ts
  frontend/src/app/common/attachment-utils.ts
  frontend/src/app/components/common/attachments-carousel.tsx
  frontend/src/app/components/containers/complaints/details/complaint-details-create.tsx
  frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx
Labels: enhancement

#227 Bump Babel Traverse to latest minor version
  backend/package-lock.json
  frontend/package-lock.json
  frontend/package.json
Labels: dependencies

#229 Dependency Upgrades
  backend/package-lock.json
  frontend/package-lock.json
  frontend/package.json
Labels: dependencies

#231 Maint/axios 1.6
  backend/package-lock.json
  backend/package.json
  frontend/package-lock.json
  frontend/package.json
Labels: dependencies

#232 Upgrade Cypress to v13
  frontend/package-lock.json
  frontend/package.json
Labels: dependencies
