Repository bcgov/nr-compliance-enforcement, pull requests merged in 2023-06, with the labels that each got.

#44 BUG-COMPENF-362: fixed weird animation when opening and closing sidebar
  frontend/src/assets/sass/layout.scss
Labels: bug

#34 COMPENF-212-Database-Backup
  .github/dependabot.yml
  .github/workflows/pr-open.yml
  backend/openshift.deploy.yml
  backend/src/main.ts
  database/openshift.deploy.yml
  frontend/openshift.deploy.yml
Labels: documentation, enhancement

#59 COMPENF-394 - Jest/Unit Test Errors
  .github/pull_request_template.md
  .github/workflows/pr-open.yml
  frontend/cypress.config.ts
  frontend/cypress/e2e/spec.cy.ts
  frontend/cypress/support/commands.ts
  frontend/src/__test__/App.test.tsx
Labels: bug

#70 Compenf 321 assign complaints details view
  .github/workflows/pr-open.yml
  backend/db/migrations/R__Create-Test-Officer.sql
  backend/src/auth/jwtauth.guard.ts
  backend/src/v1/allegation_complaint/allegation_complaint.service.spec.ts
  backend/src/v1/allegation_complaint/allegation_complaint.service.ts
  backend/src/v1/hwcr_complaint/hwcr_complaint.service.ts
  backend/src/v1/office/entities/office.entity.ts
  backend/src/v1/office/office.service.ts
  backend/src/v1/officer/officer.service.ts
  backend/src/v1/person/person.service.ts
  frontend/cypress/e2e/change-complaint-assignee-details-view.cy.ts
  frontend/cypress/e2e/change-complaint-status-details-view.cy.ts
  frontend/cypress/screenshots/change-complaint-assignee-details-view.cy.ts/Complaint Change Assignee spec - Details View -- Changes assignee of a complaint (failed) (1).png
  frontend/cypress/screenshots/change-complaint-assignee-details-view.cy.ts/Complaint Change Assignee spec - Details View -- Changes assignee of a complaint (failed).png
  frontend/cypress/screenshots/change-complaint-assignee.cy.ts/Complaint Assign Popover spec -- Changes assignee of complaint (failed).png
  frontend/src/app/components/containers/complaints/allegations/allegation-complaint-table.tsx
  frontend/src/app/components/containers/complaints/complaint-ellipsis-popover.tsx
  frontend/src/app/components/containers/complaints/details/complaint-header.tsx
  frontend/src/app/components/containers/complaints/hwcr/hwcr-complaint-table.tsx
  frontend/src/app/components/modal/instances/assign-officer-modal.tsx
  frontend/src/app/components/modal/instances/change-status-modal.tsx
  frontend/src/app/service/user-service.tsx
  frontend/src/app/store/reducers/allegation-complaint.ts
  frontend/src/app/store/reducers/assign-officers.ts
  frontend/src/app/store/reducers/complaints.ts
  frontend/src/app/store/reducers/hwcr-complaints.ts
  frontend/src/assets/sass/complaint.scss
Labels: bug, enhancement

#71 Compenf 608 refresh assignee list bug
  frontend/src/app/components/containers/complaints/details/complaint-header.tsx
  frontend/src/app/components/modal/instances/assign-officer-modal.tsx
  frontend/src/app/components/modal/modal.tsx
Labels: bug
