Repository bcgov/nr-compliance-enforcement, pull requests merged in 2024-10, with the labels that each got.

#689 chore(CE-1118): CE-1118 Add Ryan as officer for test and prod
  migrations/migrations/R__Create-Test-Data.sql
  migrations/test-only-migrations/R__Test-Data-Creation.sql
Labels: good first issue

#696 chore(CE-535): Refactor ValidationInput and ValidationSelect to use CompInput and CompSelect
  frontend/src/app/common/validation-input.tsx
  frontend/src/app/common/validation-select.tsx
  frontend/src/app/components/common/comp-input.tsx
  frontend/src/app/components/containers/complaints/details/complaint-details-create.tsx
  frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx
Labels: refactor

#705 fix: CE 1124
  .github/workflows/pr-version-bump.yml
  .github/workflows/release-branch-creation.yml
Labels: pipeline change

#702 fix: CE-917 enable autoscaling for test
  .github/workflows/merge-main.yml
  .github/workflows/merge-release.yml
  charts/app/values.yaml
Labels: bug, pipeline change

#698 fix: CE-1078 persist secret content changes between rollouts
  .github/workflows/pr-close.yml
  .github/workflows/pr-open.yml
  charts/app/Chart.lock
  charts/app/templates/_helpers.tpl
  migrations/migrations/R__Create-Test-Data.sql
  migrations/test-only-migrations/R__Test-Data-Creation.sql
Labels: bug, pipeline change

#711 fix: CE 1124
  .github/workflows/pr-version-bump.yml
  .github/workflows/release-branch-creation.yml
Labels: pipeline change

#706 chore: CE-590 standardized on actor guid
  frontend/src/app/components/containers/complaints/complaint-filter.tsx
  frontend/src/app/components/containers/complaints/outcomes/ceeb/ceeb-decision/decision-form.tsx
  frontend/src/app/components/containers/complaints/outcomes/ceeb/ceeb-decision/decision-item.tsx
  frontend/src/app/components/containers/complaints/outcomes/ceeb/ceeb-decision/decision.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-complaint-assessment.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-equipment/equipment-form.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-equipment/equipment-item.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-file-review.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-outcome-by-animal-v2.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-prevention-education.tsx
  frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/animal-outcome.tsx
  frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/create-outcome.tsx
  frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/drug-authorized-by.tsx
  frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/drug-item.tsx
  frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/edit-outcome.tsx
  frontend/src/app/components/containers/complaints/outcomes/supplemental-notes/supplemental-notes-input.tsx
  frontend/src/app/store/reducers/case-selectors.ts
  frontend/src/app/store/reducers/case-thunks.ts
  frontend/src/app/store/reducers/complaints.ts
  frontend/src/app/store/reducers/officer.ts
  migrations/test-only-migrations/R__Test-Data-Creation.sql
  migrations/test-only-migrations/V0.29.0__CE-590.sql
Labels: case_management_2

#714 fix: secret-keep
  charts/app/templates/secret.yaml
Labels: bug, pipeline change

#722 feat: CE-634
  backend/src/app.module.ts
  backend/src/types/models/case-files/assessment-details.ts
  backend/src/v1/case_file/case_file.module.ts
  backend/src/v1/case_file/case_file.service.spec.ts
  backend/src/v1/case_file/case_file.service.ts
  backend/src/v1/complaint/complaint.controller.ts
  backend/src/v1/complaint/complaint.module.ts
  backend/src/v1/linked_complaint_xref/dto/create-linked_complaint_xref.dto.ts
  backend/src/v1/linked_complaint_xref/dto/linked_complaint_xref.dto.ts
  backend/src/v1/linked_complaint_xref/dto/update-linked_complaint_xref.dto.ts
  backend/src/v1/linked_complaint_xref/entities/linked_complaint_xref.entity.ts
  backend/src/v1/linked_complaint_xref/linked_complaint_xref.controller.spec.ts
  backend/src/v1/linked_complaint_xref/linked_complaint_xref.controller.ts
  backend/src/v1/linked_complaint_xref/linked_complaint_xref.module.ts
  backend/src/v1/linked_complaint_xref/linked_complaint_xref.service.spec.ts
  backend/src/v1/linked_complaint_xref/linked_complaint_xref.service.ts
  frontend/README.md
  frontend/craco.config.ts
  frontend/cypress/e2e/change-complaint-assignee.cy.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/common/api.ts
  frontend/src/app/components/containers/complaints/complaints.tsx
  frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx
  frontend/src/app/components/containers/complaints/details/complaint-header.tsx
  frontend/src/app/components/containers/complaints/details/linked-complaint-list.tsx
  frontend/src/app/components/containers/complaints/list-items/complaint-action-items.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-complaint-assessment-link-complaint-search.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-complaint-assessment.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-outcome-report.tsx
  frontend/src/app/components/containers/complaints/webeoc-complaint-updates/webeoc-complaint-update-list.tsx
  frontend/src/app/components/modal/instances/index.ts
  frontend/src/app/components/modal/instances/quick-close-modal.tsx
  frontend/src/app/components/modal/modal.tsx
  frontend/src/app/components/modal/model-components.ts
  frontend/src/app/store/migrations.ts
  frontend/src/app/store/migrations/migration-19.ts
  frontend/src/app/store/reducers/case-thunks.ts
  frontend/src/app/store/reducers/cases.ts
  frontend/src/app/store/reducers/complaints.ts
  frontend/src/app/store/store.ts
  frontend/src/app/types/app/case-files/assessment-details.ts
  frontend/src/app/types/app/complaints/linked-complaint.ts
  frontend/src/app/types/modal/modal-types.ts
  frontend/src/app/types/outcomes/assessment.ts
  frontend/src/app/types/state/complaint-state.ts
  frontend/src/assets/sass/complaint.scss
  frontend/src/assets/sass/layout.scss
  frontend/tsconfig.json
  migrations/migrations/V0.30.2__CE-1151.sql
Labels: case_management_3

#727 chore: bump prod db size
  .github/workflows/merge-main.yml
Labels: pipeline change

#725 feat: add IaC sysdig alerts
  .github/scripts/sysdig_deploy.sh
  .github/scripts/sysdig_installed.sh
  .github/workflows/deploy-sysdig.yml
  .gitignore
  terraform/alerts_prod.tf
  terraform/alerts_test.tf
  terraform/backend.tf
  terraform/channels.tf
  terraform/provider.tf
  terraform/variables.tf
Labels: pipeline change
