Repository bcgov/nr-compliance-enforcement, pull requests merged in 2024-12, with the labels that each got.

#782 chore: CE-1288 animal action updates
  frontend/src/app/store/migrations.ts
  frontend/src/app/store/migrations/migration-23.ts
Labels: case_management_5

#794 feat: CE-1260 add Outcome Date filter
  backend/src/types/models/complaints/complaint-filter-parameters.ts
  backend/src/v1/complaint/complaint.service.ts
  frontend/src/app/components/common/filter-date.tsx
  frontend/src/app/components/containers/complaints/complaint-filter-bar.tsx
  frontend/src/app/components/containers/complaints/complaint-filter.tsx
  frontend/src/app/components/containers/complaints/complaint-list.tsx
  frontend/src/app/components/containers/complaints/complaint-map.tsx
  frontend/src/app/constants/feature-flag-types.ts
  frontend/src/app/providers/complaint-filter-provider.tsx
  frontend/src/app/store/reducers/app.ts
  frontend/src/app/store/reducers/complaints.ts
  frontend/src/app/types/app/active-filters.ts
  frontend/src/app/types/complaints/complaint-filters.ts
  frontend/src/app/types/complaints/complaint-filters/complaint-filters.ts
  frontend/src/assets/sass/complaint.scss
  migrations/migrations/R__Create-Test-Data.sql
Labels: case_management_1

#795 chore: pipeline health checks during rollout
  .github/scripts/rollout_healthcheck.sh
  .github/workflows/merge-release.yml
  .github/workflows/pr-open.yml
  .github/workflows/release-main.yml
  charts/app/templates/backend/templates/deployment.yaml
  charts/app/templates/metabase/deployment.yaml
  charts/app/templates/webeoc/templates/deployment.yaml
Labels: pipeline change

#799 feat: CE-239 Server-side Clustering
  backend/package-lock.json
  backend/package.json
  backend/src/types/models/complaints/complaint-search-parameters.ts
  backend/src/types/models/complaints/map-search-results.ts
  backend/src/v1/code-table/code-table.controller.spec.ts
  backend/src/v1/complaint/complaint.controller.ts
  backend/src/v1/complaint/complaint.service.spec.ts
  backend/src/v1/complaint/complaint.service.ts
  backend/src/v1/office/office.controller.v2.spec.ts
  backend/src/v1/officer/officer.service.ts
  backend/src/v1/person/person.controller.spec.ts
  backend/test/app.e2e-spec.ts
  backend/tsconfig.json
  charts/app/templates/backend/templates/deployment.yaml
  frontend/cypress/e2e/complaints-on-map-view.cy.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/components/common/search-input.tsx
  frontend/src/app/components/containers/complaints/complaint-filter.tsx
  frontend/src/app/components/containers/complaints/complaint-map-with-server-side-clustering.tsx
  frontend/src/app/components/containers/complaints/complaint-map.tsx
  frontend/src/app/components/containers/complaints/complaints.tsx
  frontend/src/app/components/mapping/leaflet-map-with-multiple-points.tsx
  frontend/src/app/components/mapping/leaflet-map-with-server-side-clustering.tsx
  frontend/src/app/components/mapping/spiderfy.tsx
  frontend/src/app/store/migrations.ts
  frontend/src/app/store/migrations/migration-25.ts
  frontend/src/app/store/reducers/complaints.ts
  frontend/src/app/store/store.ts
  frontend/src/app/types/complaints/complaint-filters/complaint-request-payload.ts
  frontend/src/app/types/complaints/map-return.ts
  frontend/src/app/types/state/complaint-state.ts
  frontend/src/assets/sass/maps.scss
  webeoc/package-lock.json
  webeoc/test/app.e2e-spec.ts
Labels: enhancement

#830 feat: Release/0.6.10
  backend/src/common/methods.ts
  backend/src/types/models/complaints/export-complaint-parameters.ts
  backend/src/types/models/general/attachment.ts
  backend/src/v1/complaint/complaint.service.ts
  backend/src/v1/document/document.controller.ts
  backend/src/v1/document/document.service.ts
  backend/templates/complaint/CDOGS-CEEB-COMPLAINT-TEMPLATE-v1.docx
  backend/templates/complaint/CDOGS-ERS-COMPLAINT-TEMPLATE-v1.docx
  backend/templates/complaint/CDOGS-HWCR-COMPLAINT-TEMPLATE-v1.docx
  charts/app/templates/secret.yaml
  frontend/src/app/common/validation-checkbox-group.tsx
  frontend/src/app/common/validation-phone-input.tsx
  frontend/src/app/components/common/attachments-carousel.tsx
  frontend/src/app/components/common/comp-coordinate-input.tsx
  frontend/src/app/components/common/complaint-pagination.tsx
  frontend/src/app/components/containers/admin/feature-management.tsx
  frontend/src/app/components/containers/complaints/list-items/allegation-complaint-list-item.tsx
  frontend/src/app/components/containers/complaints/list-items/wildlife-complaint-list-item.tsx
  frontend/src/app/components/containers/complaints/outcomes/ceeb/ceeb-decision/decision-item.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-complaint-assessment.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-equipment/equipment-form.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-outcome-by-animal-v2.tsx
  frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/animal-outcome.tsx
  frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/drug-authorized-by.tsx
  frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/drug-item.tsx
  frontend/src/app/components/containers/complaints/outcomes/outcome-attachments.tsx
  frontend/src/app/components/containers/zone-at-a-glance/office-user-container.tsx
  frontend/src/app/components/containers/zone-at-a-glance/zone-at-a-glance.tsx
  frontend/src/app/components/modal/instances/assign-officer-modal.tsx
  frontend/src/app/components/modal/instances/cancel-confirm-modal.tsx
  frontend/src/app/components/modal/instances/delete-confirm-modal-v2.tsx
  frontend/src/app/components/modal/instances/standalone-cancel-confirm-modal.tsx
  frontend/src/app/store/reducers/app.ts
  frontend/src/app/store/reducers/documents-thunks.ts
  frontend/src/app/types/complaints/export-complaint-input.ts
  migrations/migrations/R__create-replace-insert-action-taken.sql
  webeoc/src/webeoc-scheduler/webeoc-scheduler.service.ts
Labels: Release Branch
