Repository bcgov/nr-compliance-enforcement, pull requests merged in 2024-06, with the labels that each got.

#440 fix: CE-730 "Fate of remaining drug in vial" not showing as a required field when a drug is entered
  frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/create-outcome.tsx
  frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/drug-item.tsx
  frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/drug-used.tsx
  frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/edit-outcome.tsx
  frontend/src/app/types/app/case-files/animal-outcome/animal-outcome-input.ts
  frontend/src/app/types/app/case-files/animal-outcome/drug-used-input.ts
  frontend/src/app/types/app/complaints/outcomes/wildlife/drug-used.ts
Labels: case_management_2

#454 feat: CE-765 WebEOC In Production
  .github/workflows/merge-main.yml
Labels: pipeline change

#460 bug: Pipeline Deployment issue with Database
  .github/workflows/merge-main.yml
Labels: pipeline change

#492 chore: update packages with high vulnerability
  backend/package-lock.json
  frontend/package-lock.json
  webeoc/package-lock.json
Labels: case_management_4
