Repository bcgov/nr-compliance-enforcement, pull requests merged in 2025-05, with the labels that each got.

#1047 feat: CE-1573 Add Outcome actioned by
  backend/package.json
  backend/src/external_api/shared_data.ts
  backend/src/types/models/case-files/wildlife/wildlife-input.ts
  backend/src/types/models/code-tables/hwcr-outcome-actioned-by.ts
  backend/src/types/models/code-tables/index.ts
  backend/src/types/models/complaints/complaint-filter-parameters.ts
  backend/src/v1/code-table/code-table.service.ts
  backend/src/v1/complaint/complaint.service.ts
  backend/templates/complaint/CDOGS-HWCR-COMPLAINT-TEMPLATE-v1.docx
  backend/templates/complaint/CDOGS-PARKS-HWCR-COMPLAINT-TEMPLATE-v1.docx
  charts/app/Chart.yaml
  frontend/package.json
  frontend/src/app/components/containers/complaints/complaint-filter-bar.tsx
  frontend/src/app/components/containers/complaints/complaint-filter.tsx
  frontend/src/app/components/containers/complaints/complaint-list.tsx
  frontend/src/app/components/containers/complaints/complaint-map-with-server-side-clustering.tsx
  frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/animal-outcome.tsx
  frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/create-outcome.tsx
  frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/edit-outcome.tsx
  frontend/src/app/constants/code-table-types.ts
  frontend/src/app/constants/feature-flag-types.ts
  frontend/src/app/constants/outcomes-requiring-actioned-by.ts
  frontend/src/app/providers/complaint-filter-provider.tsx
  frontend/src/app/store/migrations/migration-30.ts
  frontend/src/app/store/reducers/app.ts
  frontend/src/app/store/reducers/case-selectors.ts
  frontend/src/app/store/reducers/case-thunks.ts
  frontend/src/app/store/reducers/code-table.ts
  frontend/src/app/store/reducers/complaints.ts
  frontend/src/app/types/app/active-filters.ts
  frontend/src/app/types/app/case-files/animal-outcome/animal-outcome-input.ts
  frontend/src/app/types/app/code-tables/hwcr-outcome-actioned-by.ts
  frontend/src/app/types/app/complaints/outcomes/wildlife/animal-outcome.ts
  frontend/src/app/types/complaints/complaint-filters.ts
  frontend/src/app/types/complaints/complaint-filters/complaint-filters.ts
  frontend/src/app/types/complaints/complaint-filters/complaint-request-payload.ts
  frontend/src/app/types/state/cases-state.ts
  frontend/src/app/types/state/code-table-state.ts
  migrations/migrations/R__Create-Test-Data.sql
  webeoc/package.json
Labels: case_management_8

#1044 feat: deploy frontend canary to emerald
  .github/workflows/merge-release.yml
  .github/workflows/pr-close.yml
  .github/workflows/pr-open.yml
  backend/package.json
  charts/app/Chart.yaml
  frontend/package.json
  webeoc/package.json
Labels: pipeline change

#1058 feat: CE-1542 Add park area to Admin page
  backend/package.json
  backend/src/types/models/code-tables/index.ts
  backend/src/types/models/people/officer.ts
  backend/src/v1/code-table/code-table.service.ts
  backend/src/v1/officer/dto/create-officer.dto.ts
  backend/src/v1/officer/dto/officer.dto.ts
  backend/src/v1/officer/entities/officer.entity.ts
  backend/src/v1/officer/officer.service.ts
  charts/app/Chart.yaml
  frontend/package.json
  frontend/src/app/components/containers/admin/user-management/edit-user.tsx
  frontend/src/app/constants/code-table-types.ts
  frontend/src/app/store/migrations.ts
  frontend/src/app/store/migrations/migration-30.ts
  frontend/src/app/store/migrations/migration-31.ts
  frontend/src/app/store/reducers/code-table-selectors.ts
  frontend/src/app/store/reducers/code-table-thunks.ts
  frontend/src/app/store/reducers/code-table.ts
  frontend/src/app/store/store.ts
  frontend/src/app/types/app/code-tables/park-area.ts
  frontend/src/app/types/person/new-officer.ts
  frontend/src/app/types/person/person.ts
  frontend/src/app/types/state/code-table-state.ts
  migrations/migrations/V0.43.0__CE-1542.sql
  webeoc/package.json
Labels: case_management_6

#1059 feat: crunchy operations for dev env
  .github/workflows/merge-release.yml
  .github/workflows/pr-close.yml
  .github/workflows/pr-open.yml
  backend/package.json
  charts/app/Chart.yaml
  frontend/package.json
  webeoc/package.json
Labels: pipeline change

#1055 feat: CE-1455
  backend/package.json
  backend/src/external_api/shared_data.ts
  backend/src/types/models/case-files/assessment/assessment-action.ts
  backend/src/types/models/case-files/assessment/assessment.ts
  backend/src/types/models/case-files/assessment/create-assessment-input.ts
  backend/src/types/models/case-files/assessment/update-assessment-input.ts
  backend/src/types/models/case-files/case-file.ts
  backend/src/types/models/case-files/equipment/equipment-details.ts
  backend/src/v1/complaint/complaint.service.ts
  backend/src/v1/officer/officer.service.ts
  backend/src/v1/shared_data/case_file/case_file.controller.ts
  backend/src/v1/shared_data/case_file/case_file.service.ts
  backend/templates/complaint/CDOGS-HWCR-COMPLAINT-TEMPLATE-v1.docx
  backend/templates/complaint/CDOGS-PARKS-ERS-COMPLAINT-TEMPLATE-v1.docx
  backend/templates/complaint/CDOGS-PARKS-GIR-COMPLAINT-TEMPLATE-v1.docx
  backend/templates/complaint/CDOGS-PARKS-HWCR-COMPLAINT-TEMPLATE-v1.docx
  charts/app/Chart.yaml
  frontend/cypress/e2e/allegation-details-create.cy.ts
  frontend/cypress/e2e/allegation-details-edit.cy.ts
  frontend/cypress/e2e/ceeb-user-complaint-decision.cy.ts
  frontend/cypress/e2e/change-complaint-status-details-view.cy.ts
  frontend/cypress/e2e/general-incident-details-create.cy.ts
  frontend/cypress/e2e/hwcr-details-create-enter-coordinates.cy.ts
  frontend/cypress/e2e/hwcr-details-create.cy.ts
  frontend/cypress/e2e/hwcr-details-edit.cy.ts
  frontend/cypress/e2e/hwcr-outcome-assessment.cy.ts
  frontend/cypress/e2e/hwcr-outcome-prev-and-educ.cy.ts
  frontend/package.json
  frontend/src/app/common/validation-checkbox-group.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-assessment/hwcr-assessment-form.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-assessment/hwcr-assessment-item.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-assessment/hwcr-assessment-link-complaint-search.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-assessment/hwcr-assessment.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-assessment/hwcr-assessments.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-complaint-assessment.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-outcome-report.tsx
  frontend/src/app/components/modal/instances/quick-close-modal.tsx
  frontend/src/app/hooks/validate-complaint.tsx
  frontend/src/app/store/reducers/case-selectors.ts
  frontend/src/app/store/reducers/case-thunks.ts
  frontend/src/app/store/reducers/cases.ts
  frontend/src/app/types/app/case-files/assessment/assessment-action.ts
  frontend/src/app/types/app/case-files/assessment/assessment.ts
  frontend/src/app/types/app/case-files/assessment/create-assessment-input.ts
  frontend/src/app/types/app/case-files/assessment/update-assessment-input.ts
  frontend/src/app/types/app/case-files/case-file.ts
  frontend/src/app/types/app/case-files/create-assessment-input.ts
  frontend/src/app/types/app/case-files/update-assessment-input.ts
  frontend/src/app/types/outcomes/assessment.ts
  frontend/src/app/types/state/cases-state.ts
  webeoc/package.json
Labels: case_management_5

#1060 feat: CE-1576-BC-Parks-filter-by-area
  backend/package.json
  backend/src/types/models/complaints/complaint-filter-parameters.ts
  backend/src/v1/complaint/complaint.service.ts
  charts/app/Chart.yaml
  frontend/package.json
  frontend/src/app/components/containers/complaints/complaint-filter.tsx
  frontend/src/app/components/containers/complaints/complaint-list.tsx
  frontend/src/app/components/containers/complaints/complaint-map-with-server-side-clustering.tsx
  frontend/src/app/providers/complaint-filter-provider.tsx
  frontend/src/app/store/reducers/complaints.ts
  frontend/src/app/types/complaints/complaint-filters.ts
  frontend/src/app/types/complaints/complaint-filters/complaint-filters.ts
  frontend/src/app/types/complaints/complaint-filters/complaint-request-payload.ts
  migrations/migrations/R__Create-Test-Data.sql
  webeoc/package.json
Labels: case_management_7

#1075 chore: Add missing zone shared email
  backend/package.json
  charts/app/Chart.yaml
  frontend/package.json
  migrations/migrations/R__Create-Test-Data.sql
  webeoc/package.json
Labels: ME ME ME ME!

#1073 feat: CE-1592 Multiple Prevention and Education
  backend/package.json
  backend/src/external_api/shared_data.ts
  backend/src/types/models/case-files/case-file.ts
  backend/src/types/models/case-files/prevention/create-prevention-input.ts
  backend/src/types/models/case-files/prevention/delete-prevention-input.ts
  backend/src/types/models/case-files/prevention/prevention-action.ts
  backend/src/types/models/case-files/prevention/prevention.ts
  backend/src/types/models/case-files/prevention/update-prevention-input.ts
  backend/src/v1/complaint/complaint.service.ts
  backend/src/v1/shared_data/case_file/case_file.controller.ts
  backend/src/v1/shared_data/case_file/case_file.service.ts
  backend/templates/complaint/CDOGS-HWCR-COMPLAINT-TEMPLATE-v1.docx
  backend/templates/complaint/CDOGS-PARKS-HWCR-COMPLAINT-TEMPLATE-v1.docx
  charts/app/Chart.yaml
  frontend/cypress/e2e/hwcr-outcome-prev-and-educ.cy.ts
  frontend/package.json
  frontend/src/app/components/containers/complaints/outcomes/hwcr-outcome-report.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-prevention-education.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-prevention/hwcr-prevention-form.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-prevention/hwcr-prevention-item.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-prevention/hwcr-prevention.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-prevention/hwcr-preventions.tsx
  frontend/src/app/components/modal/instances/quick-close-modal.tsx
  frontend/src/app/hooks/validate-complaint.tsx
  frontend/src/app/store/migrations.ts
  frontend/src/app/store/migrations/migration-34.ts
  frontend/src/app/store/reducers/case-selectors.ts
  frontend/src/app/store/reducers/case-thunks.ts
  frontend/src/app/store/reducers/cases.ts
  frontend/src/app/types/app/case-files/case-file.ts
  frontend/src/app/types/app/case-files/prevention/create-prevention-input.ts
  frontend/src/app/types/app/case-files/prevention/delete-prevention-input.ts
  frontend/src/app/types/app/case-files/prevention/prevention.ts
  frontend/src/app/types/app/case-files/prevention/update-prevention-input.ts
  frontend/src/app/types/outcomes/prevention.ts
  frontend/src/app/types/state/cases-state.ts
  frontend/src/assets/sass/outcome-report.scss
  webeoc/package.json
Labels: case_management_0, ME ME ME ME!

#1081 feat: remove metabase from pipeline temporarily and refresh sysdig alerts
  .github/scripts/sysdig_deploy.sh
  .github/workflows/deploy-sysdig.yml
  .github/workflows/merge-release.yml
  .github/workflows/release-main.yml
  backend/package.json
  charts/app/Chart.yaml
  charts/app/templates/metabase/deployment.yaml
  charts/app/templates/metabase/is.yaml
  charts/app/templates/metabase/route.yaml
  charts/app/templates/metabase/service.yaml
  charts/app/values.yaml
  frontend/package.json
  tools/terraform/alerts_prod.tf
  tools/terraform/alerts_test.tf
  tools/terraform/backend.tf
  tools/terraform/channels.tf
  tools/terraform/provider.tf
  tools/terraform/variables.tf
  webeoc/package.json
Labels: ME ME ME ME!

#1082 fix: crunchy openshift detection
  charts/crunchy/templates/PostgresCluster.yaml
Labels: ME ME ME ME!

#1077 feat: CE-114 select complaint location from map
  backend/package.json
  charts/app/Chart.yaml
  frontend/cypress/e2e/change-complaint-status-details-view.cy.ts
  frontend/cypress/e2e/hwcr-outcome-assessment.cy.ts
  frontend/package.json
  frontend/src/app/components/common/comp-coordinate-input.tsx
  frontend/src/app/components/containers/complaints/details/complaint-details-create.tsx
  frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-equipment/equipment-form.tsx
  frontend/src/app/components/modal/instances/map-modal.tsx
  webeoc/package.json
Labels: ME ME ME ME!

#1085 feat: CE-1669 Authorization Column on ERS Complaints
  backend/package-lock.json
  backend/package.json
  backend/src/types/models/complaints/allegation-complaint.ts
  backend/src/v1/complaint/complaint.service.ts
  charts/app/Chart.yaml
  frontend/cypress/e2e/complaint-list-ceeb.cy.ts
  frontend/cypress/e2e/complaint-list-cos.cy.ts
  frontend/cypress/e2e/complaint-list-parks.cy.ts
  frontend/package.json
  frontend/src/app/components/containers/complaints/headers/allegation-complaint-list-header.tsx
  frontend/src/app/components/containers/complaints/list-items/allegation-complaint-list-item.tsx
  frontend/src/app/constants/feature-flag-types.ts
  frontend/src/app/types/app/complaints/allegation-complaint.ts
  migrations/migrations/R__Create-Test-Data.sql
  webeoc/package-lock.json
  webeoc/package.json
Labels: case_management_9, ME ME ME ME!

#1086 fix: CE-1679 Small updates to referral email templates
  backend/package.json
  backend/src/email_templates/referrals.ts
  backend/src/v1/email/email.service.ts
  charts/app/Chart.yaml
  frontend/package.json
  webeoc/package.json
Labels: ME ME ME ME!

#1083 feat: CE 1622-1623 Unmapped equipment banner, copy all equipment location
  backend/package.json
  backend/src/v1/email/email.service.ts
  charts/app/Chart.yaml
  frontend/cypress/e2e/hwcr-outcome-equipment.cy.ts
  frontend/package.json
  frontend/src/app/components/common/comp-coordinate-input.tsx
  frontend/src/app/components/containers/complaints/details/complaint-details-create.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-equipment/equipment-form.tsx
  frontend/src/app/components/mapping/leaflet-map-with-point.tsx
  frontend/src/assets/sass/complaint.scss
  webeoc/package.json
Labels: ME ME ME ME!

#1093 feat: CE-1624 Lead agency of a complaint cannot edit data provided by other agency
  backend/package.json
  backend/src/external_api/shared_data.ts
  backend/src/v1/shared_data/case_file/case_file.service.ts
  charts/app/Chart.yaml
  frontend/package.json
  frontend/src/app/components/containers/complaints/outcomes/hwcr-assessment/hwcr-assessment-form.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-assessment/hwcr-assessment-item.tsx
  frontend/src/app/components/containers/complaints/outcomes/notes/note-form.tsx
  frontend/src/app/components/containers/complaints/outcomes/notes/note-item.tsx
  frontend/src/app/components/containers/complaints/outcomes/notes/note.tsx
  frontend/src/app/store/reducers/case-thunks.ts
  frontend/src/app/types/outcomes/note.ts
  webeoc/package.json
Labels: case_management_0, ME ME ME ME!

#1094 fix: CE-1693 collab can no longer add notes to a complaint
  backend/package.json
  charts/app/Chart.yaml
  frontend/package.json
  frontend/src/app/components/containers/complaints/outcomes/notes/note-item.tsx
  webeoc/package.json
Labels: ME ME ME ME!

#1098 feat: referral updates for data exports
  backend/package.json
  charts/app/Chart.yaml
  exports/ceeb_complaint_export.sql
  exports/cos_ers_complaint_export.sql
  exports/cos_hwcr_complaint_export.sql
  frontend/package.json
  webeoc/package.json
Labels: ME ME ME ME!
