Repository bcgov/nr-compliance-enforcement, pull requests merged in 2025-04, with the labels that each got.

#999 feat: CE-1362 add equipment filters
  backend/src/types/models/code-tables/equipment-status.ts
  backend/src/types/models/code-tables/index.ts
  backend/src/types/models/complaints/complaint-filter-parameters.ts
  backend/src/v1/code-table/code-table.service.ts
  backend/src/v1/complaint/complaint.service.ts
  frontend/cypress/e2e/hwcr-details-create-enter-coordinates.cy.ts
  frontend/cypress/e2e/hwcr-details-create.cy.ts
  frontend/cypress/e2e/hwcr-details-edit.cy.ts
  frontend/src/app/common/validation-multiselect.tsx
  frontend/src/app/components/containers/complaints/complaint-filter-bar.tsx
  frontend/src/app/components/containers/complaints/complaint-filter.tsx
  frontend/src/app/components/containers/complaints/complaint-list.tsx
  frontend/src/app/components/containers/complaints/complaint-map-with-server-side-clustering.tsx
  frontend/src/app/components/containers/complaints/complaints.tsx
  frontend/src/app/constants/code-table-types.ts
  frontend/src/app/providers/complaint-filter-provider.tsx
  frontend/src/app/store/migrations.ts
  frontend/src/app/store/migrations/migration-29.ts
  frontend/src/app/store/reducers/code-table-selectors.ts
  frontend/src/app/store/reducers/code-table-thunks.ts
  frontend/src/app/store/reducers/code-table.ts
  frontend/src/app/store/reducers/complaints.ts
  frontend/src/app/store/store.ts
  frontend/src/app/types/app/code-tables/equipment-status.ts
  frontend/src/app/types/complaints/complaint-filters.ts
  frontend/src/app/types/complaints/complaint-filters/complaint-filters.ts
  frontend/src/app/types/complaints/complaint-filters/complaint-request-payload.ts
  frontend/src/app/types/state/code-table-state.ts
Labels: case_management_0

#1001 fix: Remove margin from complaint edit button
  frontend/src/app/components/containers/complaints/outcomes/oucome-by-animal/animal-outcome.tsx
  frontend/src/assets/sass/complaint.scss
  frontend/src/assets/sass/outcome-report.scss
Labels: case_management_6

#1013 feat: CE-1535
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/external_api/shared_data.ts
  backend/src/middleware/maps/automapper-dto-to-entity-maps.ts
  backend/src/middleware/maps/automapper-entity-to-dto-maps.ts
  backend/src/middleware/maps/automapper-meta-data.ts
  backend/src/middleware/maps/dto-to-table-map.ts
  backend/src/types/models/complaints/update-complaint.dto.ts
  backend/src/types/models/reports/complaints/complaint-report-data.ts
  backend/src/v1/code-table/code-table.service.ts
  backend/src/v1/complaint/complaint.service.ts
  backend/src/v1/complaint/entities/complaint.entity.ts
  backend/src/v1/configuration/configuration.controller.ts
  backend/src/v1/shared_data/case_file/case_file.controller.ts
  backend/src/v1/shared_data/case_file/case_file.module.ts
  backend/src/v1/shared_data/case_file/case_file.service.spec.ts
  backend/src/v1/shared_data/case_file/case_file.service.ts
  backend/src/v1/shared_data/dto/park.dto.ts
  backend/src/v1/shared_data/shared_data.controller.ts
  backend/src/v1/shared_data/shared_data.module.ts
  backend/src/v1/shared_data/shared_data.service.ts
  backend/templates/complaint/CDOGS-CEEB-COMPLAINT-TEMPLATE-v1.docx
  backend/templates/complaint/CDOGS-ERS-COMPLAINT-TEMPLATE-v1.docx
  backend/templates/complaint/CDOGS-GIR-COMPLAINT-TEMPLATE-v1.docx
  backend/templates/complaint/CDOGS-HWCR-COMPLAINT-TEMPLATE-v1.docx
  charts/app/Chart.yaml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/components/containers/complaints/details/call-details.tsx
  frontend/src/app/components/containers/complaints/details/complaint-details-create.tsx
  frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx
  frontend/src/app/components/containers/complaints/details/complaint-details-park.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-complaint-assessment-link-complaint-search.tsx
  frontend/src/app/store/reducers/complaints.ts
  frontend/src/app/types/complaints/details/complaint-details.ts
  frontend/src/assets/sass/complaint.scss
  migrations/migrations/V0.40.1__CE-1535.sql
  migrations/test-only-migrations/R__Test-Data-Creation.sql
  webeoc/package-lock.json
  webeoc/package.json
Labels: case_management_2

#1018 feat: Add Park to List view and add Park Filter
  .github/workflows/.tests.yml
  backend/package-lock.json
  backend/package.json
  backend/src/types/models/complaints/complaint-filter-parameters.ts
  backend/src/v1/complaint/complaint.service.ts
  charts/app/Chart.yaml
  frontend/cypress.config.ts
  frontend/cypress/e2e/complaint-filters-cos.cy.ts
  frontend/cypress/e2e/complaint-filters-parks.cy.ts
  frontend/cypress/e2e/complaint-list-ceeb.cy.ts
  frontend/cypress/e2e/complaint-list-cos.cy.ts
  frontend/cypress/e2e/complaint-list-parks.cy.ts
  frontend/cypress/e2e/complaint-list.cy.ts
  frontend/cypress/support/commands.ts
  frontend/cypress/support/index.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/common/cache/park-name-cache.ts
  frontend/src/app/components/common/park.tsx
  frontend/src/app/components/containers/complaints/complaint-filter-bar.tsx
  frontend/src/app/components/containers/complaints/complaint-filter.tsx
  frontend/src/app/components/containers/complaints/complaint-list.tsx
  frontend/src/app/components/containers/complaints/complaint-map-with-server-side-clustering.tsx
  frontend/src/app/components/containers/complaints/details/call-details.tsx
  frontend/src/app/components/containers/complaints/details/complaint-details-create.tsx
  frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx
  frontend/src/app/components/containers/complaints/headers/allegation-complaint-list-header.tsx
  frontend/src/app/components/containers/complaints/headers/general-complaint-list-header.tsx
  frontend/src/app/components/containers/complaints/headers/wildlife-complaint-list-header.tsx
  frontend/src/app/components/containers/complaints/list-items/allegation-complaint-list-item.tsx
  frontend/src/app/components/containers/complaints/list-items/general-complaint-list-item.tsx
  frontend/src/app/components/containers/complaints/list-items/wildlife-complaint-list-item.tsx
  frontend/src/app/constants/feature-flag-types.ts
  frontend/src/app/providers/complaint-filter-provider.tsx
  frontend/src/app/store/reducers/app.ts
  frontend/src/app/store/reducers/complaints.ts
  frontend/src/app/types/app/active-filters.ts
  frontend/src/app/types/complaints/complaint-filters.ts
  frontend/src/app/types/complaints/complaint-filters/complaint-request-payload.ts
  migrations/migrations/R__Create-Test-Data.sql
  migrations/test-only-migrations/R__Test-Data-Creation.sql
  webeoc/package.json
Labels: case_management_7

#1031 feat: Parks specific options for Prevention and Education
  backend/package.json
  backend/src/types/models/code-tables/prevention-type.ts
  backend/src/v1/code-table/code-table.service.ts
  charts/app/Chart.yaml
  frontend/package.json
  frontend/src/app/components/containers/complaints/outcomes/hwcr-prevention-education.tsx
  frontend/src/app/store/reducers/case-thunks.ts
  frontend/src/app/store/reducers/code-table.ts
  frontend/src/app/types/app/code-tables/prevention-type.ts
  webeoc/package.json
Labels: case_management_2

#1037 feat: CE-1541 Add areas to Parks & associate park names with them
  backend/package.json
  backend/src/v1/complaint/complaint.service.ts
  backend/src/v1/shared_data/dto/park.dto.ts
  backend/src/v1/shared_data/dto/park_area.dto.ts
  backend/src/v1/shared_data/shared_data.service.ts
  charts/app/Chart.yaml
  frontend/package.json
  frontend/src/app/components/common/park.tsx
  frontend/src/assets/sass/complaint.scss
  webeoc/package.json
Labels: case_management_6

#1040 feat: Parks Templates
  backend/package.json
  backend/src/external_api/cdogs/cdogs.service.ts
  backend/src/types/configuration-codes.ts
  backend/src/v1/complaint/complaint.service.ts
  backend/templates/complaint/CDOGS-CEEB-COMPLAINT-TEMPLATE-v1.docx
  backend/templates/complaint/CDOGS-ERS-COMPLAINT-TEMPLATE-v1.docx
  backend/templates/complaint/CDOGS-GIR-COMPLAINT-TEMPLATE-v1.docx
  backend/templates/complaint/CDOGS-HWCR-COMPLAINT-TEMPLATE-v1.docx
  backend/templates/complaint/CDOGS-PARKS-ERS-COMPLAINT-TEMPLATE-v1.docx
  backend/templates/complaint/CDOGS-PARKS-GIR-COMPLAINT-TEMPLATE-v1.docx
  backend/templates/complaint/CDOGS-PARKS-HWCR-COMPLAINT-TEMPLATE-v1.docx
  charts/app/Chart.yaml
  frontend/package.json
  migrations/migrations/R__Create-Test-Data.sql
  migrations/migrations/R__reset-templates.sql
  webeoc/package.json
Labels: case_management_7
