Repository bcgov/nr-compliance-enforcement, pull requests merged in 2025-09, with the labels that each got.

#1215 feat: CE-1809 create investigation
  backend/package.json
  charts/app/Chart.yaml
  frontend/package.json
  frontend/src/app/App.tsx
  frontend/src/app/components/containers/cases/view/components/investigation-column.tsx
  frontend/src/app/components/containers/investigations/edit/investigation-edit-header.tsx
  frontend/src/app/components/containers/investigations/edit/investigation-edit.tsx
  frontend/src/generated/graphql.ts
  webeoc/package.json
Labels: case_management_3, ME ME ME ME!

#1217 feat: CE-1773, CE-1719, CE-1847 Linked Complaints
  backend/package-lock.json
  backend/package.json
  backend/src/v1/complaint/complaint.controller.ts
  backend/src/v1/linked_complaint_xref/dto/create-linked_complaint_xref.dto.ts
  backend/src/v1/linked_complaint_xref/dto/linked_complaint_xref.dto.ts
  backend/src/v1/linked_complaint_xref/entities/linked_complaint_xref.entity.ts
  backend/src/v1/linked_complaint_xref/linked_complaint_xref.controller.spec.ts
  backend/src/v1/linked_complaint_xref/linked_complaint_xref.module.ts
  backend/src/v1/linked_complaint_xref/linked_complaint_xref.service.spec.ts
  backend/src/v1/linked_complaint_xref/linked_complaint_xref.service.ts
  charts/app/Chart.yaml
  frontend/package.json
  frontend/src/app/components/common/custom-hint.scss
  frontend/src/app/components/common/custom-hint.tsx
  frontend/src/app/components/containers/cases/edit/case-edit.tsx
  frontend/src/app/components/containers/cases/view/case-view.tsx
  frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx
  frontend/src/app/components/containers/complaints/details/complaint-header.tsx
  frontend/src/app/components/containers/complaints/details/linked-complaint-list.tsx
  frontend/src/app/components/containers/complaints/list-items/complaint-action-items.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-assessment/hwcr-assessment-form.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-assessment/hwcr-assessment-link-complaint-search.tsx
  frontend/src/app/components/containers/investigations/edit/investigation-edit.tsx
  frontend/src/app/components/modal/instances/index.ts
  frontend/src/app/components/modal/instances/link-complaint-modal.tsx
  frontend/src/app/components/modal/model-components.ts
  frontend/src/app/types/app/complaints/linked-complaint.ts
  frontend/src/app/types/modal/modal-types.ts
  frontend/src/assets/sass/complaint.scss
  migrations/migrations/V0.50.0__CE-1886.sql
  migrations/migrations/V0.50.1__CE-1886-drop-constraint.sql
  migrations/migrations/V0.50.2__CE-1886-rename-timestamps.sql
  webeoc/package.json
Labels: ME ME ME ME!

#1223 fix: CE-1719 Tweaks
  backend/package.json
  charts/app/Chart.yaml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx
  frontend/src/app/components/containers/complaints/details/complaint-header.tsx
  frontend/src/app/components/containers/complaints/details/linked-complaint-list.tsx
  frontend/src/app/components/containers/complaints/list-items/complaint-action-items.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-assessment/hwcr-assessment-form.tsx
  frontend/src/app/components/modal/instances/link-complaint-modal.tsx
  webeoc/package.json
Labels: ME ME ME ME!

#1216 feat: CE-1846 restrict access for COS enforcement complaint
  backend/package.json
  backend/src/v1/complaint/complaint.controller.ts
  backend/src/v1/complaint/complaint.service.ts
  backend/src/v1/person_complaint_xref/person_complaint_xref.service.ts
  charts/app/Chart.yaml
  frontend/e2e/tests/allegation-details-restrict-access.spec.ts
  frontend/package.json
  frontend/src/app/components/containers/complaints/details/complaint-details-edit.tsx
  frontend/src/app/components/containers/complaints/details/complaint-header.tsx
  frontend/src/app/components/containers/complaints/outcomes/hwcr-assessment/hwcr-assessment-form.tsx
  frontend/src/app/components/containers/pages/not-authorized.tsx
  frontend/src/app/store/reducers/complaints.ts
  webeoc/package.json
Labels: ME ME ME ME!

#1218 feat: CE-1806 inspection details
  backend/package.json
  charts/app/Chart.yaml
  frontend/package.json
  frontend/src/app/App.tsx
  frontend/src/app/components/containers/instpections/details/index.tsx
  frontend/src/app/components/containers/instpections/details/inspection-details.tsx
  frontend/src/app/components/containers/instpections/details/inspection-header.tsx
  frontend/src/app/components/containers/instpections/inspections.tsx
  frontend/src/app/components/containers/investigations/edit/investigation-edit.tsx
  frontend/src/app/components/containers/layout/side-bar.tsx
  frontend/src/app/constants/feature-flag-types.ts
  frontend/src/generated/graphql.ts
  migrations/migrations/R__Create-Test-Data.sql
  migrations/test-only-migrations/R__Test-Data-Creation.sql
  webeoc/package.json
Labels: case_management_4, ME ME ME ME!

#1228 feat: CE-1814 case inspections
  backend/package.json
  charts/app/Chart.yaml
  frontend/package.json
  frontend/src/app/components/containers/cases/view/case-view.tsx
  frontend/src/app/components/containers/cases/view/components/inspection-card.tsx
  frontend/src/app/components/containers/cases/view/components/inspection-column.tsx
  webeoc/package.json
Labels: ME ME ME ME!

#1234 fix: CE-1856 fix numbering format in pdf exports
  .github/workflows/pr-validate.yml
  backend/package.json
  backend/src/v1/complaint/complaint.service.ts
  backend/templates/complaint/CDOGS-CEEB-COMPLAINT-TEMPLATE-v1.docx
  backend/templates/complaint/CDOGS-GIR-COMPLAINT-TEMPLATE-v1.docx
  backend/templates/complaint/CDOGS-HWCR-COMPLAINT-TEMPLATE-v1.docx
  backend/templates/complaint/CDOGS-PARKS-GIR-COMPLAINT-TEMPLATE-v1.docx
  backend/templates/complaint/CDOGS-PARKS-HWCR-COMPLAINT-TEMPLATE-v1.docx
  charts/app/Chart.yaml
  frontend/package.json
  webeoc/package.json
Labels: ME ME ME ME!

#1259 chore: Remove unused secrets
  backend-cm/dataloader/bulk-data-loader.js
  backend/dataloader/bulk-data-loader.js
  backend/package.json
  charts/app/Chart.yaml
  docker-compose.yml
  frontend/package.json
  webeoc/package.json
Labels: ME ME ME ME!

#1264 chore: Feature management search
  backend/package.json
  charts/app/Chart.yaml
  frontend/package.json
  frontend/src/app/components/containers/admin/feature-management.tsx
  webeoc/package.json
Labels: ME ME ME ME!
